### PR TITLE
Do not bundle development only code

### PR DESCRIPTION
**Pull request by frederikhors**

### CODE REVIEW

**Comment by rixo** [comment]
Well, `process` is a Node thing. Your change crashes in the browser for me, both with Rollup & Nollup. And it still ends up in the prod bundle, with the `process.env` included.

I think you're relying on behaviour that is usually provided by Webpack and, iirc, some plugin(s).

In Rollup, you'd typically use `rollup-plugin-replace` to use `process.env` like variables in the browser. I'm sure there's a plugin that can remove dead code after static analysis, but I don't know from the top of my head.

I'm not too willing to add `rollup-plugin-replace` to this template, but if you can find a good plugin that can reliably trim the `if (import.meta.hot) { ... }` from prod bundle, I think that could be a valuable and educational addition to the template.

Or is there something that I've missed entirely?

**Comment by frederikhors** [comment]
You're right.

I totally forgot I'm using this in my `rollup.config.js`:

```js
import replace from '@rollup/plugin-replace'

replace({ 'process.env.NODE_ENV': JSON.stringify(production ? 'production' : 'development') }),
```

I think it's small enough to add it in this project.

But the choice is yours. You can close if you want.

Thanks again for your commitment! You are amazing!

**Comment by rixo** [comment]
I'm not such a fan of adding replace plugin, not so much because of weight, than because it would decrease learnability by adding noise, and I'm willing to stay close to the original template.

Like I said though, I do think elimination of dead code is a core concern of HMR because of the added dev code, so I'd be willing to merge a nice solution to this problem (with minimum fuss).

Oh, and speaking of it, merge from upstream official template can be time consuming and I sometimes fall behind... :sweat_smile: If you feel like contributing, this is something that could help.

**Comment by frederikhors** [comment]
> Oh, and speaking of it, merge from upstream official template can be time consuming and I sometimes fall behind... 😅 If you feel like contributing, this is something that could help.

Oh, wow! I wanna help of course, but I don't understand... What do you mean? What to do?

**Comment by frederikhors** [comment]
I understood what you were asking.

Done in https://github.com/rixo/svelte-template-hot/pull/10.

**Pull request closed without merging**
